---
- name: Install base
  hosts: web
  become: true
  become_user: root

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: Set Hostname    
      hostname:
        name: "{{ server_name }}"

    - name: Install pip
      apt:
        name: python3-pip
        state: latest
        
    - name: Install docker pip
      pip:
       name: docker     
